// ============================================================
// SPANISH COURSE: A0 → B1  |  data.js
// Full 122-lesson curriculum. Loaded by index.html dashboard.
// Lesson status managed in localStorage by the dashboard app.
// ============================================================

const COURSE = {
  meta: {
    title: "Español: A0 → B1",
    subtitle: "Полный курс испанского — от нуля до уверенного B1",
    total_lessons: 122,
    daily_minutes: 45,
    start_date: "2026-05-20",
    target_date: "2027-05-20",
    author: "Sevr58",
    version: "1.0"
  },

  resources: [
    { name: "Language Transfer: Complete Spanish", url: "https://www.languagetransfer.org/free-courses-1#spanish", type: "audio", icon: "🎧", note: "40 бесплатных аудиоуроков. Английский → испанский. Слушать параллельно курсу." },
    { name: "Dreaming Spanish (Super Beginner)", url: "https://www.youtube.com/@DreamingSpanish", type: "video", icon: "📺", note: "Comprehensible input. Начинать с Super Beginner. Ежедневно 10–15 мин." },
    { name: "Anki — колода Polyglot (205 карточек)", url: "../polyglot_spanish.apkg", type: "anki", icon: "🃏", note: "Уже готова. Повторять каждый день по 10–15 мин." },
    { name: "News in Slow Spanish", url: "https://www.newsinslowspanish.com/", type: "podcast", icon: "🎙️", note: "Подключить с уровня A2 (≈ урок 50+)." },
    { name: "SpanishPod101", url: "https://www.spanishpod101.com/", type: "podcast", icon: "🎙️", note: "Дополнительные диалоги и аудирование." },
    { name: "Языковой Трансфер @LanguageTransfer", url: "https://www.youtube.com/@LanguageTransfer", type: "video", icon: "📺", note: "YouTube-канал автора. Правила когнатов -tion→-ción и т.д." },
    { name: "Conjuguemos — спряжения", url: "https://conjuguemos.com/", type: "practice", icon: "⚡", note: "Тренажёр глагольных форм. Использовать начиная с урока 5." },
    { name: "Forvo — произношение", url: "https://forvo.com/languages/es/", type: "tool", icon: "🔊", note: "Произношение любого испанского слова от носителей." }
  ],

  phases: [
    { id: 0, name: "Старт", name_es: "Inicio",     color: "#ffd60a", range: [0,1],    level: "A0",    months: "Нед. 1–2",    desc: "Когнаты-суперсила + произношение. Старт без страха." },
    { id: 1, name: "Основы", name_es: "Bases",     color: "#2dc653", range: [2,30],   level: "A0→A1", months: "Мес. 1–3",    desc: "Настоящее время, базовая грамматика, первый словарный запас. Уроки Polyglot." },
    { id: 2, name: "Рост",   name_es: "Progreso",  color: "#457b9d", range: [31,60],  level: "A1→A2", months: "Мес. 4–6",    desc: "Прошедшее время, будущее, условное. Истории, путешествия, работа." },
    { id: 3, name: "Прорыв", name_es: "Avance",    color: "#e63946", range: [61,100], level: "A2→B1", months: "Мес. 7–10",   desc: "Сослагательное наклонение, сложные конструкции, свободная речь." },
    { id: 4, name: "B1",     name_es: "Nivel B1",  color: "#9d4edd", range: [101,121],level: "B1",    months: "Мес. 11–12",  desc: "Консолидация, DELE B1, уверенная коммуникация." }
  ],

  blocks: [
    { id: "B0",  phase: 0, name: "Быстрый старт",               range: [0,1]    },
    { id: "B1A", phase: 1, name: "Первый контакт",               range: [2,10]   },
    { id: "B1B", phase: 1, name: "Базовая лексика",              range: [11,18]  },
    { id: "B1C", phase: 1, name: "Ключевая грамматика",          range: [19,30]  },
    { id: "B2A", phase: 2, name: "Прошедшее время",              range: [31,38]  },
    { id: "B2B", phase: 2, name: "Будущее и условное",           range: [39,43]  },
    { id: "B2C", phase: 2, name: "Больше инструментов",          range: [44,56]  },
    { id: "B2D", phase: 2, name: "Практика A2",                  range: [57,60]  },
    { id: "B3A", phase: 3, name: "Сослагательное наклонение",    range: [61,70]  },
    { id: "B3B", phase: 3, name: "Сложные времена",              range: [71,74]  },
    { id: "B3C", phase: 3, name: "Сложная коммуникация",         range: [75,90]  },
    { id: "B3D", phase: 3, name: "Навыки и практика",            range: [91,100] },
    { id: "B4A", phase: 4, name: "Беглость",                     range: [101,110]},
    { id: "B4B", phase: 4, name: "DELE B1 Подготовка",           range: [111,121]}
  ],

  lessons: [
    // ═══════════════════════════════════════════════════════════
    // PHASE 0 — QUICK START
    // ═══════════════════════════════════════════════════════════
    {
      id:"L00", num:0, phase:0, block:"B0", level:"A0", day:1, week:1,
      title:"Суперсила когнатов",
      subtitle:"2 000 испанских слов, которые ты уже знаешь",
      grammar:["cognate_rules","word_patterns"],
      vocab:["cognates_tion","cognates_ity","cognates_ous"],
      lt_episodes:[1,2,3],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Читать испанский текст вслух, узнавая знакомые слова",
      file:"lessons/L00.html", status:"improved"
    },
    {
      id:"L01", num:1, phase:0, block:"B0", level:"A0", day:2, week:1,
      title:"Звучи как испанец",
      subtitle:"Произношение: 5 гласных, проблемные согласные, ударение",
      grammar:["pronunciation","vowels","consonants","stress"],
      vocab:["phonetics"],
      lt_episodes:[4,5],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Читать слова и предложения с правильным произношением",
      file:"lessons/L01.html", status:"improved"
    },

    // ═══════════════════════════════════════════════════════════
    // PHASE 1 — FOUNDATIONS  (Block 1A: First Contact)
    // ═══════════════════════════════════════════════════════════
    {
      id:"L02", num:2, phase:1, block:"B1A", level:"A0", day:3, week:1,
      title:"Привет, ¡Hola!",
      subtitle:"Приветствия, представление, первые фразы",
      grammar:["greetings","formal_informal","gender_adjectives_intro"],
      vocab:["greetings","courtesy","names"],
      lt_episodes:[6],
      ds_level:"super_beginner",
      polyglot:1,
      speaking_focus:"Познакомиться с кем-то по-испански (полный диалог)",
      file:"lessons/L02.html", status:"improved"
    },
    {
      id:"L03", num:3, phase:1, block:"B1A", level:"A0", day:5, week:1,
      title:"Números 1–100",
      subtitle:"Числа, математика, возраст, телефоны",
      grammar:["cardinal_numbers","agreement_uno_una"],
      vocab:["numbers_1_100","math_ops","age"],
      lt_episodes:[7],
      ds_level:"super_beginner",
      polyglot:4,
      speaking_focus:"Называть числа, возраст, номер телефона",
      file:"lessons/L03.html", status:"improved"
    },
    {
      id:"L04", num:4, phase:1, block:"B1A", level:"A0", day:7, week:1,
      title:"Артикли и род существительных",
      subtitle:"El, la, un, una — мужской и женский род",
      grammar:["articles_definite","articles_indefinite","noun_gender","plural_formation"],
      vocab:["common_nouns_gendered"],
      lt_episodes:[8],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Называть предметы в комнате с правильным артиклем",
      file:"lessons/L04.html", status:"improved"
    },
    {
      id:"L05", num:5, phase:1, block:"B1A", level:"A0", day:9, week:2,
      title:"Настоящее время: глаголы на -AR",
      subtitle:"Hablar, trabajar, vivir — я говорю, ты работаешь",
      grammar:["present_indicative_ar","subject_pronouns","verb_conjugation_intro"],
      vocab:["ar_verbs_common","everyday_actions"],
      lt_episodes:[9,10],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Рассказать о своём распорядке дня",
      file:"lessons/L05.html", status:"improved"
    },
    {
      id:"L06", num:6, phase:1, block:"B1A", level:"A0", day:11, week:2,
      title:"Глаголы на -ER и -IR",
      subtitle:"Comer, beber, vivir, escribir",
      grammar:["present_indicative_er","present_indicative_ir","question_words"],
      vocab:["er_ir_verbs","question_words"],
      lt_episodes:[10,11],
      ds_level:"super_beginner",
      polyglot:2,
      speaking_focus:"Расспросить собеседника о его жизни: ¿Qué haces? ¿Dónde vives?",
      file:"lessons/L06.html", status:"improved"
    },
    {
      id:"L07", num:7, phase:1, block:"B1A", level:"A1", day:13, week:2,
      title:"Ser vs. Estar — сердце испанского",
      subtitle:"Два глагола «быть»: постоянное vs. временное",
      grammar:["ser","estar","ser_vs_estar_rules","adjectives_with_ser_estar"],
      vocab:["professions","nationalities","states_conditions"],
      lt_episodes:[12,13],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Описать себя, своё состояние, своё местонахождение",
      file:"lessons/L07.html", status:"improved"
    },
    {
      id:"L08", num:8, phase:1, block:"B1A", level:"A1", day:15, week:3,
      title:"Вопросы и отрицания",
      subtitle:"¿Hablas español? — No, no hablo español.",
      grammar:["question_formation","negation","no_tambien_tampoco"],
      vocab:["question_words_full","negation_words"],
      lt_episodes:[14],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Задать 10 вопросов и ответить на них",
      file:"lessons/L08.html", status:"improved"
    },
    {
      id:"L09", num:9, phase:1, block:"B1A", level:"A1", day:17, week:3,
      title:"Дни, месяцы, сезоны, даты",
      subtitle:"Когда? — ¿Cuándo? Время и календарь",
      grammar:["days_of_week","months","seasons","date_expressions","hay_que"],
      vocab:["calendar","date_vocab","frequency_adverbs"],
      lt_episodes:[15],
      ds_level:"super_beginner",
      polyglot:5,
      speaking_focus:"Назначить встречу, рассказать о планах на неделю",
      file:"lessons/L09.html", status:"improved"
    },
    {
      id:"L10", num:10, phase:1, block:"B1A", level:"A1", day:19, week:3,
      title:"Цвета, прилагательные, внешность",
      subtitle:"¿Cómo es? — Описывать людей и вещи",
      grammar:["adjective_agreement","adjective_placement","color_agreement"],
      vocab:["colors","physical_description","personality","size_shape"],
      lt_episodes:[16],
      ds_level:"super_beginner",
      polyglot:11,
      speaking_focus:"Описать внешность человека и характер",
      file:"lessons/L10.html", status:"improved"
    },

    // ─── Block 1B: Essential Vocabulary ─────────────────────────
    {
      id:"L11", num:11, phase:1, block:"B1B", level:"A1", day:22, week:4,
      title:"Семья и отношения",
      subtitle:"La familia — мама, папа, сестра, муж, дети",
      grammar:["possessive_adjectives_intro","family_vocabulary","yo_tengo"],
      vocab:["family","relationships","marital_status"],
      lt_episodes:[17],
      ds_level:"super_beginner",
      polyglot:4,
      speaking_focus:"Рассказать о своей семье по-испански (1–2 минуты)",
      file:"lessons/L11.html", status:"improved"
    },
    {
      id:"L12", num:12, phase:1, block:"B1B", level:"A1", day:24, week:4,
      title:"Еда и напитки",
      subtitle:"Словарь кафе и кухни. Базовые блюда",
      grammar:["articles_with_food","partitive_meaning","querer_pedir"],
      vocab:["food_basic","drinks","meals","flavors"],
      lt_episodes:[18],
      ds_level:"super_beginner",
      polyglot:13,
      speaking_focus:"Заказать блюдо в кафе, спросить что-то в меню",
      file:"lessons/L12.html", status:"improved"
    },
    {
      id:"L13", num:13, phase:1, block:"B1B", level:"A1", day:26, week:4,
      title:"Тело и здоровье",
      subtitle:"Голова, рука, живот — и как говорить «у меня болит»",
      grammar:["doler_like_gustar","tener_expressions","body_vocabulary"],
      vocab:["body_parts","health_symptoms","at_doctor"],
      lt_episodes:[19],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Объяснить врачу, что болит",
      file:"lessons/L13.html", status:"improved"
    },
    {
      id:"L14", num:14, phase:1, block:"B1B", level:"A1", day:28, week:5,
      title:"Дом: комнаты и мебель",
      subtitle:"Estar en casa — описывать жильё",
      grammar:["hay_vs_estar_location","prepositions_place","estar_location"],
      vocab:["rooms","furniture","household_items","prepositions_place"],
      lt_episodes:[20],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Описать свой дом или квартиру в Барселоне",
      file:"lessons/L14.html", status:"improved"
    },
    {
      id:"L15", num:15, phase:1, block:"B1B", level:"A1", day:30, week:5,
      title:"Одежда и покупки",
      subtitle:"¿Cuánto cuesta? — В магазине одежды",
      grammar:["llevar_ponerse","colors_with_clothes","querer_comprar"],
      vocab:["clothing","shopping","prices","sizes"],
      lt_episodes:[21],
      ds_level:"super_beginner",
      polyglot:11,
      speaking_focus:"Купить вещь в магазине: спросить размер, цену, попросить другой цвет",
      file:"lessons/L15.html", status:"improved"
    },
    {
      id:"L16", num:16, phase:1, block:"B1B", level:"A1", day:32, week:5,
      title:"Город и транспорт",
      subtitle:"¿Cómo llego? — Ориентироваться в городе",
      grammar:["ir_en_vehicle","directions_imperative_intro","estar_location_city"],
      vocab:["city_places","transport","directions","location_prepositions"],
      lt_episodes:[22],
      ds_level:"super_beginner",
      polyglot:15,
      speaking_focus:"Объяснить как добраться до места / спросить дорогу",
      file:"lessons/L16.html", status:"improved"
    },
    {
      id:"L17", num:17, phase:1, block:"B1B", level:"A1", day:34, week:6,
      title:"Числа 100+ и деньги",
      subtitle:"Cien, mil, un millón — цены, банк, обмен",
      grammar:["cardinal_numbers_100_plus","ordinal_numbers","money_expressions"],
      vocab:["numbers_100_plus","money","bank","prices_large"],
      lt_episodes:[23],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Обсудить цену квартиры, зарплату, бюджет",
      file:"lessons/L17.html", status:"improved"
    },
    {
      id:"L18", num:18, phase:1, block:"B1B", level:"A1", day:36, week:6,
      title:"Который час? Время и расписание",
      subtitle:"¿Qué hora es? — Говорить о времени",
      grammar:["telling_time","time_expressions","schedule_vocabulary","ser_for_time"],
      vocab:["time","schedule","daily_routine_time"],
      lt_episodes:[24],
      ds_level:"super_beginner",
      polyglot:5,
      speaking_focus:"Договориться о встрече, описать распорядок дня",
      file:"lessons/L18.html", status:"improved"
    },

    // ─── Block 1C: Key Grammar ────────────────────────────────────
    {
      id:"L19", num:19, phase:1, block:"B1C", level:"A1", day:39, week:7,
      title:"Hay — «есть», «находится»",
      subtitle:"Hay un banco aquí — конструкция hay и её отличие от estar",
      grammar:["hay_construction","hay_vs_estar","quantity_with_hay"],
      vocab:["existence_expressions","place_vocabulary"],
      lt_episodes:[25],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Описать что есть в твоём городе / квартире",
      file:"lessons/L19.html", status:"improved"
    },
    {
      id:"L20", num:20, phase:1, block:"B1C", level:"A1", day:41, week:7,
      title:"Tener — иметь и выражать состояния",
      subtitle:"Tengo hambre / frío / miedo — «мне хочется / холодно / страшно»",
      grammar:["tener_conjugation","tener_expressions","tener_que_obligation"],
      vocab:["tener_phrases","needs_states","obligations"],
      lt_episodes:[26],
      ds_level:"super_beginner",
      polyglot: null,
      speaking_focus:"Выразить свои потребности и состояния",
      file:"lessons/L20.html", status:"improved"
    },
    {
      id:"L21", num:21, phase:1, block:"B1C", level:"A1", day:43, week:7,
      title:"IR — идти и будущее",
      subtitle:"¿Adónde vas? Глагол ir и конструкция ir + a + infinitivo",
      grammar:["ir_conjugation","ir_a_infinitive_future","a_plus_article"],
      vocab:["destinations","future_plans"],
      lt_episodes:[27],
      ds_level:"super_beginner",
      polyglot:3,
      speaking_focus:"Рассказать о планах на неделю / на weekend",
      file:"lessons/L21.html", status:"improved"
    },
    {
      id:"L22", num:22, phase:1, block:"B1C", level:"A1", day:45, week:8,
      title:"Модальные глаголы: poder, querer, deber",
      subtitle:"Puedo, quiero, debo — могу, хочу, должен",
      grammar:["modal_verbs","poder","querer","deber","modal_plus_infinitive"],
      vocab:["modal_expressions","permission","desire","obligation"],
      lt_episodes:[28],
      ds_level:"super_beginner",
      polyglot:8,
      speaking_focus:"Выразить желание, возможность, обязанность в разных ситуациях",
      file:"lessons/L22.html", status:"improved"
    },
    {
      id:"L23", num:23, phase:1, block:"B1C", level:"A1", day:47, week:8,
      title:"Gustar и похожие глаголы",
      subtitle:"Me gusta, te encanta, le duele — «обратные» глаголы",
      grammar:["gustar_construction","encantar_molestar_doler","indirect_pronouns_intro"],
      vocab:["likes_dislikes","hobbies","preferences"],
      lt_episodes:[29],
      ds_level:"super_beginner",
      polyglot:7,
      speaking_focus:"Рассказать о своих увлечениях и предпочтениях",
      file:"lessons/L23.html", status:"improved"
    },
    {
      id:"L24", num:24, phase:1, block:"B1C", level:"A1", day:49, week:8,
      title:"Возвратные глаголы и распорядок дня",
      subtitle:"Me llamo, me levanto, me ducho — глаголы на -se",
      grammar:["reflexive_verbs","reflexive_pronouns","daily_routine_verbs"],
      vocab:["daily_routine","personal_care","reflexive_common"],
      lt_episodes:[30],
      ds_level:"super_beginner",
      polyglot:"7+12",
      speaking_focus:"Описать утренний ритуал от пробуждения до выхода из дома",
      file:"lessons/L24.html", status:"improved"
    },
    {
      id:"L25", num:25, phase:1, block:"B1C", level:"A1", day:51, week:9,
      title:"Прямые объектные местоимения",
      subtitle:"Lo, la, los, las — «его, её, их» вместо повторов",
      grammar:["direct_object_pronouns","placement_dop","lo_la_los_las"],
      vocab:["everyday_objects_with_pronouns"],
      lt_episodes:[31],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Отвечать на вопросы, избегая повторений: ¿Tienes el libro? — Sí, lo tengo.",
      file:"lessons/L25.html", status:"improved"
    },
    {
      id:"L26", num:26, phase:1, block:"B1C", level:"A1", day:53, week:9,
      title:"Косвенные объектные местоимения",
      subtitle:"Me, te, le, nos, os, les — кому, для кого",
      grammar:["indirect_object_pronouns","le_les_with_dar_decir","a_plus_pronoun_clarification"],
      vocab:["communication_verbs","giving_sending"],
      lt_episodes:[32],
      ds_level:"beginner",
      polyglot:6,
      speaking_focus:"Написать сообщение и рассказать кому что сказал / отправил",
      file:"lessons/L26.html", status:"improved"
    },
    {
      id:"L27", num:27, phase:1, block:"B1C", level:"A1", day:55, week:9,
      title:"Указательные местоимения",
      subtitle:"Este, ese, aquel — этот, тот, вон тот",
      grammar:["demonstrative_adjectives","demonstrative_pronouns","distance_concept"],
      vocab:["distance_expressions","pointing_language"],
      lt_episodes:[33],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Выбирать товар в магазине, указывать на предметы",
      file:"lessons/L27.html", status:"improved"
    },
    {
      id:"L28", num:28, phase:1, block:"B1C", level:"A1", day:57, week:10,
      title:"Притяжательные местоимения",
      subtitle:"Mi, tu, su, nuestro — мой, твой, его, наш",
      grammar:["possessive_adjectives","possessive_pronouns","stressed_possessives"],
      vocab:["ownership_expressions","family_belongings"],
      lt_episodes:[34],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Обсудить чьи вещи, где что лежит, кому что принадлежит",
      file:"lessons/L28.html", status:"improved"
    },
    {
      id:"L29", num:29, phase:1, block:"B1C", level:"A1", day:59, week:10,
      title:"Предлоги",
      subtitle:"En, de, a, con, por, para, sin, sobre — главные предлоги",
      grammar:["prepositions_main","por_vs_para_intro","a_personal","de_possession"],
      vocab:["preposition_phrases","location_prepositions"],
      lt_episodes:[35],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Описать местонахождение, объяснить цель действия",
      file:"lessons/L29.html", status:"improved"
    },
    {
      id:"L30", num:30, phase:1, block:"B1C", level:"A1", day:62, week:10,
      title:"Повторение A1 — Говорим о себе",
      subtitle:"Итоговая практика: свободный разговор на всех темах Phase 1",
      grammar:["review_a1_grammar"],
      vocab:["review_a1_vocab"],
      lt_episodes:[36],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"15-минутный монолог и диалог: представление, семья, день, планы",
      file:"lessons/L30.html", status:"improved"
    },

    // ═══════════════════════════════════════════════════════════
    // PHASE 2 — EXPANDING  (Block 2A: The Past)
    // ═══════════════════════════════════════════════════════════
    {
      id:"L31", num:31, phase:2, block:"B2A", level:"A1", day:65, week:11,
      title:"Pretérito Indefinido — правильные глаголы",
      subtitle:"Ayer comí, hablé, viví — «вчера я поел, поговорил, прожил»",
      grammar:["preterite_regular_ar","preterite_regular_er_ir","preterite_time_expressions"],
      vocab:["past_time_expressions","past_actions"],
      lt_episodes:[37],
      ds_level:"beginner",
      polyglot:3,
      speaking_focus:"Рассказать что ты делал вчера / на прошлой неделе",
      file:"lessons/L31.html", status:"improved"
    },
    {
      id:"L32", num:32, phase:2, block:"B2A", level:"A1", day:67, week:11,
      title:"Pretérito Indefinido — неправильные глаголы",
      subtitle:"Fui, hice, tuve, dije — самые важные неправильные формы",
      grammar:["preterite_irregular_common","preterite_ir_ser_same","preterite_spelling_changes"],
      vocab:["irregular_preterite_verbs"],
      lt_episodes:[38],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Рассказать биографию известного человека или свою",
      file:"lessons/L32.html", status:"improved"
    },
    {
      id:"L33", num:33, phase:2, block:"B2A", level:"A2", day:69, week:11,
      title:"Pretérito Imperfecto — правильные глаголы",
      subtitle:"Cuando era niño, vivía en... — «когда я был ребёнком»",
      grammar:["imperfect_regular","imperfect_uses_habitual","imperfect_description"],
      vocab:["childhood_vocab","habitual_past_expressions"],
      lt_episodes:[39],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Рассказать о детстве и привычках прошлого",
      file:"lessons/L33.html", status:"improved"
    },
    {
      id:"L34", num:34, phase:2, block:"B2A", level:"A2", day:71, week:12,
      title:"Pretérito Imperfecto — неправильные и ser/ir/ver",
      subtitle:"Era, iba, veía — три исключения + устойчивые выражения",
      grammar:["imperfect_irregular_ser_ir_ver","imperfect_continuous_estaba"],
      vocab:["past_description_vocab"],
      lt_episodes:[40],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Описать сцену из прошлого: где был, что происходило вокруг",
      file:"lessons/L34.html", status:"improved"
    },
    {
      id:"L35", num:35, phase:2, block:"B2A", level:"A2", day:73, week:12,
      title:"Pretérito Perfecto — «я уже сделал»",
      subtitle:"He comido, has ido, ha llegado — опыт и недавние события",
      grammar:["perfect_tense_formation","past_participle_regular","past_participle_irregular","haber_conjugation"],
      vocab:["experience_expressions","recently_time_words"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot:6,
      speaking_focus:"Рассказать о своём жизненном опыте: ¿Has estado en España?",
      file:"lessons/L35.html", status:"improved"
    },
    {
      id:"L36", num:36, phase:2, block:"B2A", level:"A2", day:75, week:12,
      title:"Indefinido vs. Imperfecto — когда что использовать",
      subtitle:"Главный выбор испанского прошлого",
      grammar:["preterite_vs_imperfect_rules","context_clues","background_vs_action"],
      vocab:["story_connectors","time_contrast_words"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Пересказать историю, правильно чередуя оба прошедших времени",
      file:"lessons/L36.html", status:"improved"
    },
    {
      id:"L37", num:37, phase:2, block:"B2A", level:"A2", day:77, week:13,
      title:"Рассказываем истории",
      subtitle:"Primero, luego, después, al final — связки для нарратива",
      grammar:["narrative_connectors","sequencing","past_tenses_combined"],
      vocab:["story_vocabulary","narrative_markers"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Рассказать историю из жизни (2–3 минуты) с началом, серединой, концом",
      file:"lessons/L37.html", status:"improved"
    },
    {
      id:"L38", num:38, phase:2, block:"B2A", level:"A2", day:79, week:13,
      title:"Выражения времени в прошлом",
      subtitle:"Ayer, hace tres días, el año pasado, desde que — временна́я карта",
      grammar:["past_time_expressions_full","hace_preterite","desde_hace","cuando_clauses"],
      vocab:["time_expressions_past","duration_expressions"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Точно указывать временные рамки в рассказе",
      file:"lessons/L38.html", status:"improved"
    },

    // ─── Block 2B: Future & Conditional ────────────────────────
    {
      id:"L39", num:39, phase:2, block:"B2B", level:"A2", day:82, week:14,
      title:"Ближайшее будущее: ir + a + infinitivo",
      subtitle:"Voy a estudiar, vamos a comer — «собираюсь, планирую»",
      grammar:["ir_a_infinitive_detailed","future_plans","intentions"],
      vocab:["future_time_expressions","plans_vocab"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot:3,
      speaking_focus:"Рассказать о планах на ближайшие дни/месяцы",
      file:"lessons/L39.html", status:"improved"
    },
    {
      id:"L40", num:40, phase:2, block:"B2B", level:"A2", day:84, week:14,
      title:"Futuro Simple — простое будущее",
      subtitle:"Hablaré, comerás, vivirá — «буду, будешь, будет»",
      grammar:["future_simple_regular","future_simple_irregular","future_probability"],
      vocab:["future_time_expressions","predictions"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Делать предсказания и говорить о далёких планах",
      file:"lessons/L40.html", status:"improved"
    },
    {
      id:"L41", num:41, phase:2, block:"B2B", level:"A2", day:86, week:14,
      title:"Condicional — «бы»",
      subtitle:"Hablaría, comería, viviría — «говорил бы, ел бы»",
      grammar:["conditional_regular","conditional_irregular","conditional_uses_politeness"],
      vocab:["politeness_expressions","hypothetical_situations"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Вежливые просьбы и гипотетические ситуации: ¿Podría ayudarme?",
      file:"lessons/L41.html", status:"improved"
    },
    {
      id:"L42", num:42, phase:2, block:"B2B", level:"A2", day:88, week:15,
      title:"Планы, намерения, мечты",
      subtitle:"Espero, pienso, me gustaría — говорить о будущем красиво",
      grammar:["esperar_pensar_querer_plus_infinitive","me_gustaria","future_expressions_varied"],
      vocab:["dreams_goals","future_vocab","ambitions"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Рассказать о мечтах, целях и планах на ближайший год",
      file:"lessons/L42.html", status:"improved"
    },
    {
      id:"L43", num:43, phase:2, block:"B2B", level:"A2", day:90, week:15,
      title:"Сравнения и превосходная степень",
      subtitle:"Más que, menos que, tan como, el más — сравниваем всё",
      grammar:["comparatives_regular","comparatives_irregular_bueno_malo","superlatives","tan_como"],
      vocab:["comparison_expressions","quality_adjectives"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot:9,
      speaking_focus:"Сравнить два города, два варианта, два человека",
      file:"lessons/L43.html", status:"improved"
    },

    // ─── Block 2C: More Grammar Tools ───────────────────────────
    {
      id:"L44", num:44, phase:2, block:"B2C", level:"A2", day:93, week:16,
      title:"Двойные объектные местоимения",
      subtitle:"Me lo da, te los envía — объединяем прямые и косвенные",
      grammar:["double_object_pronouns","order_dop_iop","le_se_change"],
      vocab:["giving_receiving_expressions"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Отвечать кратко: ¿Me lo puedes dar? — Sí, te lo doy ahora.",
      file:"lessons/L44.html", status:"improved"
    },
    {
      id:"L45", num:45, phase:2, block:"B2C", level:"A2", day:95, week:16,
      title:"Imperativo — повелительное наклонение",
      subtitle:"¡Habla! ¡Come! ¡Escucha! — приказы, советы, инструкции",
      grammar:["imperative_positive_tu","imperative_usted","imperative_irregular","imperative_negative"],
      vocab:["instructions","advice","commands"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot:12,
      speaking_focus:"Дать инструкцию, совет или рецепт",
      file:"lessons/L45.html", status:"improved"
    },
    {
      id:"L46", num:46, phase:2, block:"B2C", level:"A2", day:97, week:16,
      title:"Глаголы с чередованием E→IE, O→UE",
      subtitle:"Quiero, puedo, entiendo, vuelvo — «сапожки»",
      grammar:["stem_change_e_ie","stem_change_o_ue","boot_verb_pattern"],
      vocab:["stem_changing_verbs_common"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot:14,
      speaking_focus:"Использовать 20 самых частотных неправильных глаголов в разговоре",
      file:"lessons/L46.html", status:"improved"
    },
    {
      id:"L47", num:47, phase:2, block:"B2C", level:"A2", day:99, week:17,
      title:"Глаголы с чередованием E→I",
      subtitle:"Pido, sirvo, sigo — третья группа «сапожков»",
      grammar:["stem_change_e_i","e_i_in_preterite_also","seguir_pedir_servir"],
      vocab:["e_i_stem_verbs"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot: null,
      speaking_focus:"Заказывать еду и услуги: ¿Me sirves más agua?",
      file:"lessons/L47.html", status:"improved"
    },
    {
      id:"L48", num:48, phase:2, block:"B2C", level:"A2", day:101, week:17,
      title:"Наречия образа действия",
      subtitle:"Rápidamente, claramente, bien, mal — «как?»",
      grammar:["adverbs_formation_mente","irregular_adverbs","adverb_placement"],
      vocab:["manner_adverbs","degree_adverbs","frequency_adverbs"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot:9,
      speaking_focus:"Описать как выполняется действие, насколько что-то хорошо",
      file:"lessons/L48.html", status:"improved"
    },
    {
      id:"L49", num:49, phase:2, block:"B2C", level:"A2", day:103, week:17,
      title:"Относительные придаточные",
      subtitle:"Que, quien, donde, lo que — «который, которая, где»",
      grammar:["relative_pronouns_que","relative_quien","relative_donde","lo_que"],
      vocab:["relative_clause_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Делать сложные описания людей и мест без пауз",
      file:"lessons/L49.html", status:"improved"
    },
    {
      id:"L50", num:50, phase:2, block:"B2C", level:"A2", day:105, week:18,
      title:"Отрицания: nada, nadie, nunca",
      subtitle:"No tengo nada / No hay nadie / Nunca lo haré — double negation",
      grammar:["double_negation_spanish","ninguno_ninguna","jamás","tampoco"],
      vocab:["negation_vocabulary","negative_expressions"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot:10,
      speaking_focus:"Выражать отрицание эмфатически и в разных контекстах",
      file:"lessons/L50.html", status:"improved"
    },
    {
      id:"L51", num:51, phase:2, block:"B2C", level:"A2", day:107, week:18,
      title:"Квантификаторы и неопределённые слова",
      subtitle:"Mucho, poco, bastante, algo, todo, cada — «количество»",
      grammar:["quantifiers","indefinite_pronouns","todo_toda_todos","cada"],
      vocab:["quantifier_expressions","indefinite_vocabulary"],
      lt_episodes:[],
      ds_level:"beginner",
      polyglot:10,
      speaking_focus:"Говорить о количестве, охвате, частичности",
      file:"lessons/L51.html", status:"improved"
    },
    {
      id:"L52", num:52, phase:2, block:"B2C", level:"A2", day:109, week:18,
      title:"Ser vs. Estar — глубокое погружение",
      subtitle:"Estar muerto vs ser malo — тонкие случаи и устойчивые выражения",
      grammar:["ser_estar_advanced_cases","ser_estar_adjective_meaning_change","locative_ser_events"],
      vocab:["ser_estar_fixed_expressions","adjective_meaning_changes"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Правильно выбирать ser/estar в 20 ловушечных ситуациях",
      file:"lessons/L52.html", status:"improved"
    },
    {
      id:"L53", num:53, phase:2, block:"B2C", level:"A2", day:111, week:19,
      title:"Пассивный залог: основы",
      subtitle:"Se vende, se habla español, fue construido — три способа",
      grammar:["passive_se","passive_ser_past_participle","impersonal_se"],
      vocab:["passive_context_vocabulary","signs_announcements"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Читать объявления и вывески, понимать пассивные конструкции",
      file:"lessons/L53.html", status:"improved"
    },
    {
      id:"L54", num:54, phase:2, block:"B2C", level:"A2", day:113, week:19,
      title:"Эмоции и чувства",
      subtitle:"Estar enamorado, sentirse triste, ponerse nervioso",
      grammar:["emotion_verbs","ponerse_quedarse_volverse","expressing_feelings"],
      vocab:["emotions_vocabulary","feelings_expressions","mood_changes"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Говорить о своих и чужих эмоциях в разных ситуациях",
      file:"lessons/L54.html", status:"improved"
    },
    {
      id:"L55", num:55, phase:2, block:"B2C", level:"A2", day:115, week:19,
      title:"Работа и профессии",
      subtitle:"¿En qué trabajas? Офис, карьера, поиск работы",
      grammar:["profession_vocabulary","trabajo_en_vs_soy","work_expressions"],
      vocab:["professions","workplace","job_hunting","work_actions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Рассказать о своей работе и задать вопросы о работе собеседника",
      file:"lessons/L55.html", status:"improved"
    },
    {
      id:"L56", num:56, phase:2, block:"B2C", level:"A2", day:118, week:20,
      title:"Повторение A2 — большой разговор",
      subtitle:"Итоговая практика Phase 2 — все темы и времена вместе",
      grammar:["review_a2_grammar"],
      vocab:["review_a2_vocab"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Интервью — ответить на 20 вопросов о прошлом, настоящем и будущем",
      file:"lessons/L56.html", status:"improved"
    },

    // ─── Block 2D: Practice ──────────────────────────────────────
    {
      id:"L57", num:57, phase:2, block:"B2D", level:"A2", day:120, week:20,
      title:"Практика: в ресторане",
      subtitle:"Полная симуляция — от входа до чаевых",
      grammar:["restaurant_language","formal_requests","ordering_phrases"],
      vocab:["restaurant_full","menu_vocabulary","payment"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot:13,
      speaking_focus:"Провести полный ресторанный разговор: резервация, заказ, жалоба, оплата",
      file:"lessons/L57.html", status:"improved"
    },
    {
      id:"L58", num:58, phase:2, block:"B2D", level:"A2", day:122, week:20,
      title:"Практика: путешествие и отель",
      subtitle:"Аэропорт, отель, проблемы в поездке — всё по-испански",
      grammar:["travel_language","hotel_expressions","problems_complaints"],
      vocab:["travel_full","airport","hotel","transport"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot:15,
      speaking_focus:"Пройти сценарий: прилёт → отель → проблема → решение",
      file:"lessons/L58.html", status:"improved"
    },
    {
      id:"L59", num:59, phase:2, block:"B2D", level:"A2", day:124, week:21,
      title:"Практика: рассказ о себе",
      subtitle:"Свободное говорение — 5 минут о себе без остановок",
      grammar:["extended_monologue","connecting_ideas","self_presentation"],
      vocab:["personal_narrative_vocab"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot:16,
      speaking_focus:"Монолог 5 минут: кто я, откуда, чем занимаюсь, мечты, планы",
      file:"lessons/L59.html", status:"improved"
    },
    {
      id:"L60", num:60, phase:2, block:"B2D", level:"A2", day:127, week:21,
      title:"Контрольная точка A2 — MOCK TEST",
      subtitle:"Проверяем весь уровень A2 — чтение, аудирование, письмо, говорение",
      grammar:["test_a2"],
      vocab:["test_a2"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Тест + честная самооценка по CEFR A2 criteria",
      file:"lessons/L60.html", status:"improved"
    },

    // ═══════════════════════════════════════════════════════════
    // PHASE 3 — INTERMEDIATE  (Block 3A: Subjunctive)
    // ═══════════════════════════════════════════════════════════
    {
      id:"L61", num:61, phase:3, block:"B3A", level:"A2", day:130, week:22,
      title:"Сослагательное наклонение — введение",
      subtitle:"Что такое subjuntivo и зачем он нужен",
      grammar:["subjunctive_concept","indicative_vs_subjunctive","trigger_verbs_intro"],
      vocab:["subjunctive_trigger_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Понять разницу между реальностью и желанием",
      file:"lessons/L61.html", status:"improved"
    },
    {
      id:"L62", num:62, phase:3, block:"B3A", level:"B1", day:132, week:22,
      title:"Subjuntivo presente — правильные глаголы",
      subtitle:"Hable, coma, viva — формы и первые конструкции",
      grammar:["present_subjunctive_regular","present_subjunctive_formation_rule"],
      vocab:["common_subjunctive_triggers"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Выражать желания для других: Quiero que vengas.",
      file:"lessons/L62.html", status:"improved"
    },
    {
      id:"L63", num:63, phase:3, block:"B3A", level:"B1", day:134, week:23,
      title:"Subjuntivo presente — неправильные глаголы",
      subtitle:"Sea, esté, haya, vaya, sepa, dé — исключения",
      grammar:["present_subjunctive_irregular","go_verbs_subjunctive"],
      vocab:["irregular_subjunctive_verbs"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Использовать неправильные формы в живой речи",
      file:"lessons/L63.html", status:"improved"
    },
    {
      id:"L64", num:64, phase:3, block:"B3A", level:"B1", day:136, week:23,
      title:"Subjuntivo — желания и просьбы",
      subtitle:"Quiero que..., Espero que..., Le pido que... — WEIRDO triggers",
      grammar:["subjunctive_wishes","subjunctive_requests","querer_esperar_pedir_que"],
      vocab:["wish_request_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Выражать желания и просьбы через subjuntivo",
      file:"lessons/L64.html", status:"improved"
    },
    {
      id:"L65", num:65, phase:3, block:"B3A", level:"B1", day:138, week:23,
      title:"Subjuntivo — сомнение и отрицание",
      subtitle:"No creo que..., Dudo que..., No es verdad que...",
      grammar:["subjunctive_doubt","subjunctive_negated_belief","dudar_creer_negar"],
      vocab:["doubt_denial_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Выражать сомнение и несогласие деликатно",
      file:"lessons/L65.html", status:"improved"
    },
    {
      id:"L66", num:66, phase:3, block:"B3A", level:"B1", day:140, week:24,
      title:"Subjuntivo — эмоции",
      subtitle:"Me alegra que..., Es una lástima que..., Odio que...",
      grammar:["subjunctive_emotion","emotion_triggers","alegrarse_sentir_molestar"],
      vocab:["emotion_trigger_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Реагировать на новости с эмоцией + subjuntivo",
      file:"lessons/L66.html", status:"improved"
    },
    {
      id:"L67", num:67, phase:3, block:"B3A", level:"B1", day:142, week:24,
      title:"Subjuntivo — безличные выражения",
      subtitle:"Es importante que..., Es necesario que..., Es posible que...",
      grammar:["subjunctive_impersonal","es_important_necesario_probable","impersonal_se"],
      vocab:["impersonal_expressions","recommendation_language"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Давать рекомендации и говорить о необходимости",
      file:"lessons/L67.html", status:"improved"
    },
    {
      id:"L68", num:68, phase:3, block:"B3A", level:"B1", day:144, week:24,
      title:"Subjuntivo vs. Indicativo — алгоритм выбора",
      subtitle:"Когда subjuntivo, когда indicativo — чёткое правило",
      grammar:["subj_vs_ind_decision_tree","que_clauses_rule","creo_que_no_creo_que"],
      vocab:["opinion_belief_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Избегать ошибок выбора наклонения в 30 тренировочных предложениях",
      file:"lessons/L68.html", status:"improved"
    },
    {
      id:"L69", num:69, phase:3, block:"B3A", level:"B1", day:146, week:25,
      title:"Subjuntivo — придаточные времени",
      subtitle:"Cuando llegues, hasta que termines, antes de que vengas",
      grammar:["subjunctive_time_clauses","cuando_hasta_antes_despues","future_time_subj"],
      vocab:["time_conjunction_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Строить планы с условными временными рамками",
      file:"lessons/L69.html", status:"improved"
    },
    {
      id:"L70", num:70, phase:3, block:"B3A", level:"B1", day:148, week:25,
      title:"Imperfecto de Subjuntivo — знакомство",
      subtitle:"Si tuviera..., Quisiera..., Si fuera tú... — вежливость и гипотезы",
      grammar:["imperfect_subjunctive_forms","si_plus_imperfect_subj","quisiera_pudiera"],
      vocab:["polite_requests","hypothetical_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Вежливо просить и выражать гипотетические желания",
      file:"lessons/L70.html", status:"improved"
    },

    // ─── Block 3B: Advanced Tenses ───────────────────────────────
    {
      id:"L71", num:71, phase:3, block:"B3B", level:"B1", day:151, week:26,
      title:"Pluscuamperfecto — «уже сделал до...»",
      subtitle:"Había comido, habían llegado — давнопрошедшее время",
      grammar:["pluperfect_tense","pluperfect_formation","pluperfect_uses"],
      vocab:["sequence_past_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Описывать действия, завершившиеся до другого прошлого события",
      file:"lessons/L71.html", status:"improved"
    },
    {
      id:"L72", num:72, phase:3, block:"B3B", level:"B1", day:153, week:26,
      title:"Condicional Compuesto — «сделал бы»",
      subtitle:"Habría hecho, habrías ido — условное прошедшее",
      grammar:["conditional_perfect","conditional_perfect_formation","hypothetical_past"],
      vocab:["regret_hypothetical_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Говорить о сожалениях и нереализованных возможностях",
      file:"lessons/L72.html", status:"improved"
    },
    {
      id:"L73", num:73, phase:3, block:"B3B", level:"B1", day:155, week:26,
      title:"Futuro Perfecto — «уже сделаю к тому моменту»",
      subtitle:"Habré terminado cuando llegues — будущее к точке",
      grammar:["future_perfect_formation","future_perfect_uses","future_probability_perfect"],
      vocab:["future_perfect_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Говорить о завершении дел к определённому сроку",
      file:"lessons/L73.html", status:"improved"
    },
    {
      id:"L74", num:74, phase:3, block:"B3B", level:"B1", day:157, week:27,
      title:"Последовательность времён",
      subtitle:"Как времена сочетаются между собой — общая карта",
      grammar:["sequence_of_tenses","tense_mapping_chart","reported_speech_tense_shift"],
      vocab:["tense_sequence_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Читать сложный текст и правильно трактовать все временны́е формы",
      file:"lessons/L74.html", status:"improved"
    },

    // ─── Block 3C: Complex Communication ────────────────────────
    {
      id:"L75", num:75, phase:3, block:"B3C", level:"B1", day:160, week:27,
      title:"Выражение мнения",
      subtitle:"Creo que, en mi opinión, desde mi punto de vista, me parece que",
      grammar:["opinion_expressions","hedging_language","opinion_phrases_formal_informal"],
      vocab:["opinion_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Высказать мнение по 5 спорным темам, аргументировать",
      file:"lessons/L75.html", status:"improved"
    },
    {
      id:"L76", num:76, phase:3, block:"B3C", level:"B1", day:162, week:27,
      title:"Согласие и несогласие",
      subtitle:"Tienes razón / No estoy de acuerdo / Es verdad que... pero...",
      grammar:["agreement_disagreement","concession_language","partial_agreement"],
      vocab:["agreement_phrases","disagreement_phrases","debate_language"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Дискуссия: поддержать и оспорить мнение собеседника",
      file:"lessons/L76.html", status:"improved"
    },
    {
      id:"L77", num:77, phase:3, block:"B3C", level:"B1", day:164, week:28,
      title:"Причина и следствие",
      subtitle:"Porque, como, ya que, por eso, por tanto, así que",
      grammar:["cause_connectors","effect_connectors","porque_vs_por","como_causal"],
      vocab:["cause_effect_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Объяснить причины своих решений и их последствия",
      file:"lessons/L77.html", status:"improved"
    },
    {
      id:"L78", num:78, phase:3, block:"B3C", level:"B1", day:166, week:28,
      title:"Уступка и контраст",
      subtitle:"Aunque, sin embargo, a pesar de, no obstante, pero vs sino",
      grammar:["concession_aunque","contrast_connectors","pero_vs_sino","a_pesar_de"],
      vocab:["contrast_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Выражать противоречия и уступки в сложных высказываниях",
      file:"lessons/L78.html", status:"improved"
    },
    {
      id:"L79", num:79, phase:3, block:"B3C", level:"B1", day:168, week:28,
      title:"Цель и результат",
      subtitle:"Para que, con el fin de, de modo que, hasta que",
      grammar:["purpose_para_que","purpose_para_infinitive","result_de_modo_que"],
      vocab:["purpose_result_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Объяснить цель своих действий и желаемый результат",
      file:"lessons/L79.html", status:"improved"
    },
    {
      id:"L80", num:80, phase:3, block:"B3C", level:"B1", day:170, week:29,
      title:"Условные предложения I — реальные",
      subtitle:"Si estudias, aprenderás — Si + Present + Future",
      grammar:["conditional_sentences_type1","si_clauses_real","real_conditions"],
      vocab:["conditional_expressions_real"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Строить реальные условия: обещания, угрозы, планы",
      file:"lessons/L80.html", status:"improved"
    },
    {
      id:"L81", num:81, phase:3, block:"B3C", level:"B1", day:172, week:29,
      title:"Условные предложения II — гипотетические",
      subtitle:"Si tuviera dinero, viajaría — Si + Imperfect Subj + Conditional",
      grammar:["conditional_sentences_type2","si_clauses_hypothetical","unreal_conditions"],
      vocab:["hypothetical_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Говорить о нереальных сценариях: если бы ты был президентом...",
      file:"lessons/L81.html", status:"improved"
    },
    {
      id:"L82", num:82, phase:3, block:"B3C", level:"B1", day:174, week:29,
      title:"Косвенная речь",
      subtitle:"Dijo que..., Me preguntó si..., Me pidió que...",
      grammar:["reported_speech","tense_backshift","reported_questions","reported_commands"],
      vocab:["reporting_verbs"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Пересказать разговор или новость от третьего лица",
      file:"lessons/L82.html", status:"improved"
    },
    {
      id:"L83", num:83, phase:3, block:"B3C", level:"B1", day:176, week:30,
      title:"Герундий — -ando/-iendo",
      subtitle:"Estoy comiendo, llevo tres horas estudiando, sin decir nada",
      grammar:["gerund_formation","gerund_with_estar","llevar_hace_with_gerund","gerund_as_adverb"],
      vocab:["gerund_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Говорить о текущих действиях и процессах",
      file:"lessons/L83.html", status:"improved"
    },
    {
      id:"L84", num:84, phase:3, block:"B3C", level:"B1", day:178, week:30,
      title:"Инфинитивные конструкции",
      subtitle:"Al llegar, después de comer, antes de dormir, sin pensar",
      grammar:["infinitive_constructions","al_plus_infinitive","preposition_plus_infinitive"],
      vocab:["infinitive_phrase_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Описывать последовательность действий элегантно",
      file:"lessons/L84.html", status:"improved"
    },
    {
      id:"L85", num:85, phase:3, block:"B3C", level:"B1", day:180, week:30,
      title:"Пассив с se",
      subtitle:"Se habla español, se venden pisos, se busca camarero",
      grammar:["impersonal_se_detailed","passive_se_agreement","passive_se_vs_active"],
      vocab:["signs_announcements_se","impersonal_contexts"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Понимать объявления и говорить о процессах без субъекта",
      file:"lessons/L85.html", status:"improved"
    },
    {
      id:"L86", num:86, phase:3, block:"B3C", level:"B1", day:182, week:31,
      title:"Медиа и технологии",
      subtitle:"Internet, redes sociales, noticias, aplicaciones",
      grammar:["technology_vocabulary_grammar"],
      vocab:["technology","social_media","news","apps","digital_life"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Обсудить цифровую жизнь, соцсети, новости",
      file:"lessons/L86.html", status:"improved"
    },
    {
      id:"L87", num:87, phase:3, block:"B3C", level:"B1", day:184, week:31,
      title:"Экология и природа",
      subtitle:"Medio ambiente, cambio climático, reciclaje",
      grammar:["environment_vocabulary_grammar"],
      vocab:["environment","nature","climate","recycling","sustainability"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Обсудить экологические проблемы и решения",
      file:"lessons/L87.html", status:"improved"
    },
    {
      id:"L88", num:88, phase:3, block:"B3C", level:"B1", day:186, week:31,
      title:"Общество и базовая политика",
      subtitle:"Gobierno, democracia, igualdad, derechos — для обсуждений",
      grammar:["society_vocabulary_grammar"],
      vocab:["society","politics_basic","rights","current_affairs_terms"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Высказаться на социальную тему на 2–3 минуты",
      file:"lessons/L88.html", status:"improved"
    },
    {
      id:"L89", num:89, phase:3, block:"B3C", level:"B1", day:188, week:32,
      title:"Здоровье и медицина",
      subtitle:"Síntomas, medicamentos, hospital — расширенный медицинский словарь",
      grammar:["health_vocabulary_advanced"],
      vocab:["health_advanced","medical_terms","pharmacy","lifestyle"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Описать симптомы, понять назначение врача",
      file:"lessons/L89.html", status:"improved"
    },
    {
      id:"L90", num:90, phase:3, block:"B3C", level:"B1", day:190, week:32,
      title:"Культура и искусство",
      subtitle:"Cine, música, arte, literatura — говорим о культуре",
      grammar:["culture_vocabulary_grammar","talking_about_art"],
      vocab:["arts","cinema","music","literature","cultural_events"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Порекомендовать фильм, книгу, выставку по-испански",
      file:"lessons/L90.html", status:"improved"
    },

    // ─── Block 3D: Skills & Practice ────────────────────────────
    {
      id:"L91", num:91, phase:3, block:"B3D", level:"B1", day:193, week:33,
      title:"Практика: телефонный разговор",
      subtitle:"Звонок в отель, врачу, в компанию — формальный телефонный испанский",
      grammar:["phone_language","formal_telephone_expressions"],
      vocab:["telephone_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Сделать формальный звонок: записаться, уточнить, пожаловаться",
      file:"lessons/L91.html", status:"improved"
    },
    {
      id:"L92", num:92, phase:3, block:"B3D", level:"B1", day:195, week:33,
      title:"Практика: описание фотографии",
      subtitle:"En la imagen se puede ver... — DELE B1 speaking task",
      grammar:["photo_description_language","spatial_description","speculation_language"],
      vocab:["photo_description_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Описать 3 разные фотографии по 90 секунд каждую",
      file:"lessons/L92.html", status:"improved"
    },
    {
      id:"L93", num:93, phase:3, block:"B3D", level:"B1", day:197, week:33,
      title:"Практика: мини-презентация",
      subtitle:"Подготовить и провести 3-минутное выступление",
      grammar:["presentation_language","structuring_speech","introduction_conclusion"],
      vocab:["presentation_vocabulary","discourse_markers"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Презентация на тему по выбору: 3 мин, с вводом и выводом",
      file:"lessons/L93.html", status:"pending"
    },
    {
      id:"L94", num:94, phase:3, block:"B3D", level:"B1", day:199, week:34,
      title:"Практика: формальное письмо и email",
      subtitle:"Estimado señor..., En respuesta a..., Le saluda atentamente",
      grammar:["formal_letter_structure","email_language","formal_vs_informal_writing"],
      vocab:["formal_writing_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Написать деловое письмо (запрос информации о визе / жилье / работе)",
      file:"lessons/L94.html", status:"pending"
    },
    {
      id:"L95", num:95, phase:3, block:"B3D", level:"B1", day:201, week:34,
      title:"Практика: понимание новостей",
      subtitle:"Скоростное чтение и аудирование новостных текстов",
      grammar:["news_reading_strategies","scanning_skimming","news_vocabulary_patterns"],
      vocab:["news_vocabulary","current_events_language"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Пересказать новость своими словами",
      file:"lessons/L95.html", status:"pending"
    },
    {
      id:"L96", num:96, phase:3, block:"B3D", level:"B1", day:203, week:34,
      title:"Практика: обсуждение фильма / сериала",
      subtitle:"¿Te gustó? ¿Qué te pareció? — говорим о кино",
      grammar:["review_language","expressing_opinion_culture","plot_summary_language"],
      vocab:["cinema_vocabulary","review_expressions"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Дать развёрнутый отзыв о фильме, сериале, книге",
      file:"lessons/L96.html", status:"pending"
    },
    {
      id:"L97", num:97, phase:3, block:"B3D", level:"B1", day:205, week:35,
      title:"Практика: дебаты",
      subtitle:"Аргументировать, защищать позицию, слушать оппонента",
      grammar:["debate_structures","argumentation_language","rebuttal_phrases"],
      vocab:["debate_vocabulary","argument_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Дебаты: выбрать сторону и отстоять за 5 мин",
      file:"lessons/L97.html", status:"pending"
    },
    {
      id:"L98", num:98, phase:3, block:"B3D", level:"B1", day:207, week:35,
      title:"Практика: история путешествия",
      subtitle:"Рассказать о поездке — прошлое, впечатления, рекомендации",
      grammar:["travel_narrative","past_tenses_combined","recommendation_language"],
      vocab:["travel_narrative_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"5-минутный рассказ о реальном или воображаемом путешествии",
      file:"lessons/L98.html", status:"pending"
    },
    {
      id:"L99", num:99, phase:3, block:"B3D", level:"B1", day:209, week:35,
      title:"Практика: собеседование на работу",
      subtitle:"¿Por qué quiere trabajar aquí? — интервью на испанском",
      grammar:["interview_language","formal_register_active","self_promotion_language"],
      vocab:["job_interview_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Полное собеседование: представление, вопросы, ответы",
      file:"lessons/L99.html", status:"pending"
    },
    {
      id:"L100", num:100, phase:3, block:"B3D", level:"B1", day:212, week:36,
      title:"Контрольная точка A2→B1 — MILESTONE",
      subtitle:"Полная оценка прогресса по всем 4 навыкам",
      grammar:["test_b1_entry"],
      vocab:["test_b1_entry"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Самооценка по CEFR B1 — честно зафиксировать уровень",
      file:"lessons/L100.html", status:"pending"
    },

    // ═══════════════════════════════════════════════════════════
    // PHASE 4 — B1 MASTERY
    // ═══════════════════════════════════════════════════════════
    {
      id:"L101", num:101, phase:4, block:"B4A", level:"B1", day:215, week:37,
      title:"Связность речи — дискурсивные маркеры",
      subtitle:"Por un lado..., sin embargo..., en definitiva... — звучать как носитель",
      grammar:["discourse_markers_full","cohesion_devices","register_awareness"],
      vocab:["discourse_markers"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Длинный монолог с полной связностью и без слов-паразитов",
      file:"lessons/L101.html", status:"pending"
    },
    {
      id:"L102", num:102, phase:4, block:"B4A", level:"B1", day:218, week:37,
      title:"Формальный и неформальный регистры",
      subtitle:"Tío vs. señor — когда что уместно",
      grammar:["register_formal_informal","tuteo_ustedeo","formal_informal_vocabulary"],
      vocab:["register_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Один сценарий в двух регистрах: с другом и с начальником",
      file:"lessons/L102.html", status:"pending"
    },
    {
      id:"L103", num:103, phase:4, block:"B4A", level:"B1", day:220, week:38,
      title:"Идиомы и устойчивые выражения",
      subtitle:"No hay mal que por bien no venga — 30 самых частотных идиом",
      grammar:["idioms","fixed_expressions","collocations"],
      vocab:["idioms_top30","common_collocations"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Использовать 10 идиом в живом разговоре",
      file:"lessons/L103.html", status:"pending"
    },
    {
      id:"L104", num:104, phase:4, block:"B4A", level:"B1", day:222, week:38,
      title:"Ложные друзья переводчика",
      subtitle:"Embarazada ≠ embarrassed — 40 ловушек для русских и англоязычных",
      grammar:["false_friends_english_spanish","false_cognates","correct_usage"],
      vocab:["false_friends_list"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Тест на ложных друзей и правильное употребление",
      file:"lessons/L104.html", status:"pending"
    },
    {
      id:"L105", num:105, phase:4, block:"B4A", level:"B1", day:224, week:38,
      title:"Испания vs. Латинская Америка",
      subtitle:"Vosotros vs. ustedes, vos, distintas palabras — regional variety",
      grammar:["regional_differences_grammar","vosotros_vs_ustedes","vos_conjugation"],
      vocab:["regional_vocabulary_differences"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Понять акцент и лексику разных стран",
      file:"lessons/L105.html", status:"pending"
    },
    {
      id:"L106", num:106, phase:4, block:"B4A", level:"B1", day:226, week:39,
      title:"Юмор и игра слов",
      subtitle:"¿Entiendes el chiste? — почему понимание юмора = настоящее владение языком",
      grammar:["wordplay","puns","humor_structures","cultural_references"],
      vocab:["humor_vocabulary","cultural_references_spain"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Понять 5 испанских шуток и объяснить почему они смешные",
      file:"lessons/L106.html", status:"pending"
    },
    {
      id:"L107", num:107, phase:4, block:"B4A", level:"B1", day:228, week:39,
      title:"Стратегии чтения B1",
      subtitle:"Как читать аутентичные тексты: статьи, блоги, инструкции",
      grammar:["reading_strategies","inference","context_vocabulary_guessing"],
      vocab:["reading_comprehension_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Прочитать аутентичную статью и обсудить её",
      file:"lessons/L107.html", status:"pending"
    },
    {
      id:"L108", num:108, phase:4, block:"B4A", level:"B1", day:230, week:39,
      title:"Стратегии аудирования B1",
      subtitle:"Shadowing, диктовка, заполнение пропусков — техники понимания на слух",
      grammar:["listening_strategies","note_taking_spanish","inference_from_audio"],
      vocab:["listening_context_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Прослушать подкаст на испанском и пересказать содержание",
      file:"lessons/L108.html", status:"pending"
    },
    {
      id:"L109", num:109, phase:4, block:"B4A", level:"B1", day:232, week:40,
      title:"Письменные навыки B1",
      subtitle:"Сочинение, эссе, рассказ — структура и стиль",
      grammar:["writing_structure","essay_language","narrative_writing","paragraph_structure"],
      vocab:["writing_vocabulary","linking_words_writing"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Написать эссе 150 слов на любую тему (время: 20 минут)",
      file:"lessons/L109.html", status:"pending"
    },
    {
      id:"L110", num:110, phase:4, block:"B4A", level:"B1", day:234, week:40,
      title:"Разговорная беглость",
      subtitle:"Заполнители паузы, periphrasis, circumlocution — говорить без остановок",
      grammar:["fluency_strategies","filler_words","circumlocution","repair_strategies"],
      vocab:["filler_expressions","communication_strategies"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Говорить 10 минут без подготовки на незнакомую тему",
      file:"lessons/L110.html", status:"pending"
    },

    // ─── Block 4B: DELE B1 Exam Prep ────────────────────────────
    {
      id:"L111", num:111, phase:4, block:"B4B", level:"B1", day:237, week:41,
      title:"DELE B1: говорение — личные темы",
      subtitle:"Себя, семья, привычки, воспоминания — готовимся к устной части",
      grammar:["dele_speaking_personal_topics"],
      vocab:["personal_topics_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Mock speaking task: 4 минуты на личную тему с интерактивом",
      file:"lessons/L111.html", status:"pending"
    },
    {
      id:"L112", num:112, phase:4, block:"B4B", level:"B1", day:240, week:41,
      title:"DELE B1: говорение — работа и повседневная жизнь",
      subtitle:"Работа, транспорт, жильё, покупки — типичные DELE-темы",
      grammar:["dele_speaking_daily_life"],
      vocab:["daily_life_b1_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Mock: ситуационный диалог + описание фото",
      file:"lessons/L112.html", status:"pending"
    },
    {
      id:"L113", num:113, phase:4, block:"B4B", level:"B1", day:243, week:42,
      title:"DELE B1: говорение — путешествия и туризм",
      subtitle:"Viajes, turismo, cultura — говорить о разных странах",
      grammar:["travel_speaking_b1"],
      vocab:["travel_tourism_b1"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Mock: планировать поездку в Испанию с аргументами",
      file:"lessons/L113.html", status:"pending"
    },
    {
      id:"L114", num:114, phase:4, block:"B4B", level:"B1", day:246, week:42,
      title:"DELE B1: говорение — социальные темы",
      subtitle:"Medio ambiente, trabajo, tecnología — B1-level social topics",
      grammar:["social_topics_b1"],
      vocab:["social_issues_b1"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Mock: обсудить социальную проблему с аргументами за и против",
      file:"lessons/L114.html", status:"pending"
    },
    {
      id:"L115", num:115, phase:4, block:"B4B", level:"B1", day:249, week:43,
      title:"DELE B1: чтение — практика",
      subtitle:"4 типа заданий: множественный выбор, соответствие, пропуски",
      grammar:["reading_comprehension_strategies_b1"],
      vocab:["reading_test_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Полный DELE B1 reading section (45 мин)",
      file:"lessons/L115.html", status:"pending"
    },
    {
      id:"L116", num:116, phase:4, block:"B4B", level:"B1", day:252, week:43,
      title:"DELE B1: аудирование — практика",
      subtitle:"Monólogos, conversaciones, anuncios — все типы заданий",
      grammar:["listening_comprehension_strategies_b1"],
      vocab:["listening_test_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Полный DELE B1 listening section (35 мин)",
      file:"lessons/L116.html", status:"pending"
    },
    {
      id:"L117", num:117, phase:4, block:"B4B", level:"B1", day:255, week:44,
      title:"DELE B1: письмо — неформальное письмо",
      subtitle:"Carta informal, correo a amigo — структура и клише",
      grammar:["informal_writing_b1","letter_structure","informal_register_writing"],
      vocab:["informal_letter_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Написать неформальное письмо другу (150–180 слов, 30 мин)",
      file:"lessons/L117.html", status:"pending"
    },
    {
      id:"L118", num:118, phase:4, block:"B4B", level:"B1", day:258, week:44,
      title:"DELE B1: письмо — формальный текст",
      subtitle:"Carta formal / artículo — структура, клише, оценка",
      grammar:["formal_writing_b1","article_structure","formal_letter_b1"],
      vocab:["formal_writing_b1_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Написать формальную жалобу или статью (150–180 слов, 30 мин)",
      file:"lessons/L118.html", status:"pending"
    },
    {
      id:"L119", num:119, phase:4, block:"B4B", level:"B1", day:261, week:45,
      title:"DELE B1: полный пробный экзамен (часть 1)",
      subtitle:"Чтение + Аудирование — 80 минут в режиме экзамена",
      grammar:["mock_exam_b1_part1"],
      vocab:["exam_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Тест в реальных условиях",
      file:"lessons/L119.html", status:"pending"
    },
    {
      id:"L120", num:120, phase:4, block:"B4B", level:"B1", day:264, week:45,
      title:"DELE B1: полный пробный экзамен (часть 2)",
      subtitle:"Письмо + Говорение — 90 минут в режиме экзамена",
      grammar:["mock_exam_b1_part2"],
      vocab:["exam_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Письменная + устная части под таймер",
      file:"lessons/L120.html", status:"pending"
    },
    {
      id:"L121", num:121, phase:4, block:"B4B", level:"B1", day:267, week:46,
      title:"🎉 Финал: Un año de español",
      subtitle:"Ты дошёл. Говори. Слушай. Живи по-испански.",
      grammar:["celebration","next_steps_b1_plus","real_world_resources"],
      vocab:["next_level_vocabulary"],
      lt_episodes:[],
      ds_level:"intermediate",
      polyglot: null,
      speaking_focus:"Финальный монолог: что изменилось за год — по-испански, 5 минут",
      file:"lessons/L121.html", status:"pending"
    }
  ]
};
